#!/bin/sh

# A dmenu wrapper script for system functions.

# For non-systemd init systems.
case "$(readlink -f /sbin/init)" in
	*runit*) hib="sudo -A zzz" ;;
	*openrc*) reb="sudo -A openrc-shutdown -r"; shut="sudo -A openrc-shutdown -p" ;;
esac

cmds="\
         Bloquear                                                	slock
         Cerrar sesion	kill -TERM $(pgrep -u $USER "\bdwm$")
♻        Recargar dwm	kill -HUP $(pgrep -u $USER "\bdwm$")
         Hibernar	slock ${hib:-systemctl suspend-then-hibernate -i}
         Reicnicar	${reb:-sudo -A reboot}
         Apagar	${shut:-sudo -A shutdown -h now}"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
