#!/usr/bin/env bash

. "${HOME}/.cache/wal/colors.sh"
reload_dunst() {
    pkill dunst
    dunst \
    	-geom 350x5-0+30 \
	-frame_width 1 \
        -frame_color "${color2}" \
        -lf "${color7}" \
        -bf "${color7}" \
        -cf "${color7}" \
        -nf "${color7}" &
}
reload_dunst